apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-forno-ingress
  labels:
{{ include "common.standard.labels" .  | indent 4 }}
    component: forno
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    # Allows WS connections to be 20 minutes long, see https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#websockets
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1200"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1200"
spec:
  rules:
  - host: {{ .Release.Namespace }}-forno.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: tx-nodes
            port:
              number: 8545
      - path: /ws
        pathType: ImplementationSpecific
        backend:
          service:
            name: tx-nodes
            port:
              number: 8546
  tls:
  - hosts:
    - {{ .Release.Namespace }}-forno.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Namespace }}-forno-web-tls
