apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "konga.fullname" . }}-snapshot
  labels:
    app.kubernetes.io/name: {{ include "konga.name" . }}
    helm.sh/chart: {{ include "konga.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  kong_node.data: |
    module.exports = [
        {
            "name": "Kong",
            "type": "default",
            "kong_admin_url": "http://{{ .Values.kong.service }}:{{ .Values.kong.admin_port }}",
            "health_checks": false,
            "active" : true,
        }
    ]
  snapshot.json: |
    {
      "createdUser": null,
      "updatedUser": null,
      "id": 1,
      "name": "kong-restored-snapshot",
      "kong_node_name": "kong",
      "kong_node_url": "http://kong:8001",
      "kong_version": "2.4.1",
      "data": {
        "services": [
          {
            "connect_timeout": 60000,
            "read_timeout": 60000,
            "name": "status",
            "id": "90a37cb9-2c01-472b-8fff-715835e56156",
            "host": "localhost",
            "created_at": 1623859719,
            "updated_at": 1623859719,
            "retries": 5,
            "path": null,
            "tls_verify_depth": null,
            "port": 8000,
            "ca_certificates": null,
            "client_certificate": null,
            "tls_verify": null,
            "tags": [],
            "protocol": "http",
            "write_timeout": 60000,
            "extras": {
              "id": 3,
              "service_id": "90a37cb9-2c01-472b-8fff-715835e56156",
              "kong_node_id": "2",
              "description": null,
              "tags": null,
              "createdAt": "2021-06-16T16:08:39.000Z",
              "updatedAt": "2021-06-16T16:08:39.000Z",
              "createdUser": null,
              "updatedUser": null
            }
          },
          {
            "connect_timeout": 60000,
            "read_timeout": 60000,
            "name": "Forno",
            "id": "d98c9e59-dc44-4bad-81ca-d399724462b0",
            "host": "baklava-fullnodes-rpc.baklava",
            "created_at": 1623232145,
            "updated_at": 1623318621,
            "retries": 5,
            "path": null,
            "tls_verify_depth": null,
            "port": 8545,
            "ca_certificates": null,
            "client_certificate": null,
            "tls_verify": null,
            "tags": [],
            "protocol": "http",
            "write_timeout": 60000,
            "extras": {
              "id": 1,
              "service_id": "d98c9e59-dc44-4bad-81ca-d399724462b0",
              "kong_node_id": "2",
              "description": null,
              "tags": null,
              "createdAt": "2021-06-09T09:49:05.000Z",
              "updatedAt": "2021-06-09T09:49:05.000Z",
              "createdUser": null,
              "updatedUser": null
            }
          }
        ],
        "routes": [
          {
            "service": {
              "id": "90a37cb9-2c01-472b-8fff-715835e56156"
            },
            "name": "health-check",
            "paths": [
              "/status",
              "/status*"
            ],
            "methods": [
              "GET"
            ],
            "sources": null,
            "destinations": null,
            "created_at": 1623859737,
            "updated_at": 1624360220,
            "path_handling": "v0",
            "protocols": [
              "http",
              "https"
            ],
            "id": "37f4e0db-fbc9-4aa3-9f47-5c957c54efdc",
            "tags": null,
            "request_buffering": true,
            "response_buffering": true,
            "hosts": null,
            "snis": null,
            "regex_priority": 100,
            "https_redirect_status_code": 426,
            "preserve_host": false,
            "strip_path": true,
            "headers": null
          },
          {
            "service": {
              "id": "d98c9e59-dc44-4bad-81ca-d399724462b0"
            },
            "name": "forno",
            "paths": [
              "/",
              "/*"
            ],
            "methods": [
              "GET",
              "POST",
              "PUT"
            ],
            "sources": null,
            "destinations": null,
            "created_at": 1623232306,
            "updated_at": 1624360203,
            "path_handling": "v0",
            "protocols": [
              "http"
            ],
            "id": "eaa4fa2b-cd10-4c61-a2ac-6831adcd0752",
            "tags": null,
            "request_buffering": true,
            "response_buffering": true,
            "hosts": null,
            "snis": null,
            "regex_priority": 10,
            "https_redirect_status_code": 426,
            "preserve_host": false,
            "strip_path": true,
            "headers": null
          }
        ],
        "consumers": [
          {
            "id": "1532538d-cb47-48fa-8a8e-b21952644a6e",
            "custom_id": null,
            "username": "anonymous",
            "tags": [],
            "created_at": 1623404756,
            "credentials": {
              "key-auths": []
            }
          },
          {
            "id": "bdfbe991-2e69-4d50-bf79-4681be7f5949",
            "custom_id": null,
            "username": "jcortejoso",
            "tags": [],
            "created_at": 1623404316,
            "credentials": {
              "key-auths": [
                {
                  "id": "13d3c5c0-d3bf-4205-a9b4-2072b81ac8b0",
                  "key": "secret",
                  "consumer": {
                    "id": "bdfbe991-2e69-4d50-bf79-4681be7f5949"
                  },
                  "ttl": null,
                  "tags": null,
                  "created_at": 1623404508
                }
              ]
            }
          }
        ],
        "plugins": [
          {
            "id": "18ccb4e4-b09c-4251-af1d-d3367f7ca667",
            "service": {
              "id": "90a37cb9-2c01-472b-8fff-715835e56156"
            },
            "enabled": true,
            "name": "request-termination",
            "config": {
              "message": "ok",
              "body": null,
              "content_type": null,
              "status_code": 200
            },
            "created_at": 1623859751,
            "consumer": null,
            "protocols": [
              "grpc",
              "grpcs",
              "http",
              "https"
            ],
            "tags": null,
            "route": null
          },
          {
            "id": "5d4f343a-1a40-4901-87bd-e839788e075b",
            "service": null,
            "enabled": true,
            "name": "key-auth",
            "config": {
              "key_in_body": false,
              "hide_credentials": false,
              "key_names": [
                "apikey"
              ],
              "key_in_header": true,
              "run_on_preflight": true,
              "anonymous": "1532538d-cb47-48fa-8a8e-b21952644a6e",
              "key_in_query": true
            },
            "created_at": 1623406677,
            "consumer": null,
            "protocols": [
              "grpc",
              "grpcs",
              "http",
              "https"
            ],
            "tags": null,
            "route": null
          },
          {
            "id": "6893a5ba-460f-4eb3-86fb-243b7f16025c",
            "service": null,
            "enabled": true,
            "name": "rate-limiting",
            "config": {
              "limit_by": "ip",
              "redis_timeout": 2000,
              "redis_database": 0,
              "redis_host": null,
              "path": null,
              "second": null,
              "minute": 10,
              "policy": "cluster",
              "day": null,
              "month": null,
              "fault_tolerant": true,
              "hide_client_headers": false,
              "header_name": null,
              "redis_port": 6379,
              "hour": null,
              "year": null,
              "redis_password": null
            },
            "created_at": 1623235507,
            "consumer": {
              "id": "1532538d-cb47-48fa-8a8e-b21952644a6e"
            },
            "protocols": [
              "grpc",
              "grpcs",
              "http",
              "https"
            ],
            "tags": null,
            "route": null
          },
          {
            "id": "7c6cb1c1-e19e-46fa-9fc9-d854db08d965",
            "service": null,
            "enabled": false,
            "name": "request-termination",
            "config": {
              "message": "OK",
              "body": null,
              "content_type": null,
              "status_code": 200
            },
            "created_at": 1623859319,
            "consumer": null,
            "protocols": [
              "grpc",
              "grpcs",
              "http",
              "https"
            ],
            "tags": null,
            "route": null
          },
          {
            "id": "852846f2-eefe-4157-ba10-43a2e870bce1",
            "service": null,
            "enabled": true,
            "name": "rate-limiting",
            "config": {
              "limit_by": "ip",
              "redis_timeout": 2000,
              "redis_database": 0,
              "redis_host": null,
              "path": null,
              "second": null,
              "minute": 100,
              "policy": "cluster",
              "day": null,
              "month": null,
              "fault_tolerant": true,
              "hide_client_headers": false,
              "header_name": null,
              "redis_port": 6379,
              "hour": null,
              "year": null,
              "redis_password": null
            },
            "created_at": 1623406844,
            "consumer": {
              "id": "bdfbe991-2e69-4d50-bf79-4681be7f5949"
            },
            "protocols": [
              "grpc",
              "grpcs",
              "http",
              "https"
            ],
            "tags": null,
            "route": null
          },
          {
            "id": "f09b5ebc-68b3-40d5-b1f7-2af4dc689bd6",
            "service": null,
            "enabled": true,
            "name": "request-termination",
            "config": {
              "message": "ok",
              "body": null,
              "content_type": null,
              "status_code": 200
            },
            "created_at": 1623859799,
            "consumer": null,
            "protocols": [
              "grpc",
              "grpcs",
              "http",
              "https"
            ],
            "tags": null,
            "route": {
              "id": "37f4e0db-fbc9-4aa3-9f47-5c957c54efdc"
            }
          }
        ],
        "acls": [
          {
            "id": "57187a97-d48b-4128-b007-281c0ed33659",
            "group": "noratelimit",
            "consumer": {
              "id": "bdfbe991-2e69-4d50-bf79-4681be7f5949"
            },
            "tags": null,
            "created_at": 1623404350
          }
        ],
        "upstreams": [],
        "certificates": [],
        "snis": []
      },
      "createdAt": "2021-06-22T11:14:49.000Z",
      "updatedAt": "2021-06-22T11:14:49.000Z"
    }