[default]
src = 'contracts'
out = 'out'
test = 'test-sol'
libs = [
    'lib',
    'node_modules',
]
remappings = [
    'openzeppelin-solidity/=node_modules/openzeppelin-solidity/',
    'solidity-bytes-utils/=node_modules/solidity-bytes-utils/',
    'forge-std/=lib/celo-foundry/lib/forge-std/src/',
    'ds-test/=lib/celo-foundry/lib/forge-std/lib/ds-test/src/',
    'celo-foundry/=lib/celo-foundry/src/'
]

no_match_contract = "RandomTest"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config