imagePullPolicy: IfNotPresent
blockscout:
  indexer:
    db:
      proxy:
        resources:
          requests:
            memory: 2Gi
            cpu: 1
    pool_size: 100
    resources:
      requests:
        memory: 4Gi
        cpu: 2
    metrics:
      enabled: true
  api:
    autoscaling:
      maxReplicas: 1
      minReplicas: 1
      target:
        cpu: 70
    db:
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 700m
    pool_size: 10
    resources:
      requests:
        memory: 500Mi
        cpu: 500m
  web:
    host: blockscoutmycelo-blockscout3.celo-testnet.org
    autoscaling:
      maxReplicas: 1
      minReplicas: 1
      target:
        cpu: 70
    db:
      proxy:
        resources:
          requests:
            memory: 500Mi
            cpu: 700m
    pool_size: 10
    resources:
      requests:
        memory: 250M
        cpu: 500m
    recaptchaSecretName: blockscoutmycelo-blockscout-recaptcha
  metrics:
    enabled: false
