apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    app: celo-ubi-api
    chart: celo-ubi-api
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MNEMONIC: {{ .Values.celoubi.api.mnemonic | b64enc | quote }}
