apiVersion: v1
kind: Service
metadata:
  name: {{ template "eksportisto.name" . }}
  labels:
    component: eksportisto
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    component: eksportisto
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "eksportisto.name" . }}-service-account
  labels:
    component: eksportisto
    release: {{ .Release.Name }}
data:
  serviceAccount.json: {{ .Values.serviceAccountBase64 | b64dec | quote }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "eksportisto.name" . }}
  labels:
    app: eksportisto
    chart: eksportisto
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: eksportisto
spec:
  serviceName: {{ template "eksportisto.name" . }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  podManagementPolicy: Parallel
  replicas: 1
  selector:
    matchLabels:
      app: eksportisto
      release: {{ .Release.Name }}
      component: eksportisto
  template:
    metadata:
      labels:
        app: eksportisto
        release: {{ .Release.Name }}
        component: eksportisto
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      initContainers:
      - name: init-sensitive-accounts
        image: alpine
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ['cp', '-L', '/var/config/sensitive-accounts.json', '/root/.eksportisto/']
        volumeMounts:
        - name: data
          mountPath: /root/.eksportisto
        - name: config
          mountPath: /var/config
      containers:
      - name: eksportisto-{{ .Values.deploymentSuffix }}
        image: {{ .Values.imageRepository }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        args:
          - "-nodeUri={{ .Values.web3Provider }}"
          - "-datadir=/root/.eksportisto"
          - "-sensitiveAccounts=/root/.eksportisto/sensitive-accounts.json"
          - "-output=pubsub"
          - "-pubsub-topic-id={{ .Values.topicId }}"
          - "-pubsub-project-id={{ .Values.projectId }}"
        env:
        - name: GOGC
          value: "11300"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/root/serviceAccount.json"
        resources:
          requests:
            memory: 2Gi
            cpu: 1800m
        ports:
        - name: prometheus
          containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /root/.eksportisto
        - name: config
          mountPath: /var/config
        - name: service-account
          mountPath: /root/serviceAccount.json
          subPath: serviceAccount.json
      - name: eksportisto-{{ .Values.deploymentSuffix }}-alpine
        image: alpine:latest
        command: ['sleep', 'infinity']
        volumeMounts:
        - name: data
          mountPath: /root/.eksportisto
        - name: service-account
          mountPath: /root/serviceAccount.json
          subPath: serviceAccount.json
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: eksportisto-{{ .Values.deploymentSuffix }}-config
      - name: service-account
        configMap:
          name: {{ template "eksportisto.name" . }}-service-account
