apiVersion: v1
kind: Secret
metadata:
  name: dbPassword
  labels:
{{ include "labels" . | indent 4 }}
type: Opaque
data:
  dbPassword: {{ .Values.signer.dbinclude "common.env-var" (dict "name" "DB_PASSWORD" "dict" .Values.signer.db "value_name" "password") | indent 10 }}
  {{ $identity.privateKey }}
