apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: odis-signer-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: {{ .Release.Namespace }}-web-tls
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "name" . }}
            port:
              number: 3000
