apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Namespace }}-celostats-frontend
  labels:
    app: celostats
    chart: celostats
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: celostats-frontend
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Release.Namespace }}-celostats.{{ .Values.domain.name }}.org
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Namespace }}-celostats-frontend
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Release.Namespace }}-celostats.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Namespace }}-celostats-frontend-tls
