apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-log-agent
  namespace: fluentd
spec:
 selector:
   matchLabels:
     name: fluentd-log-agent
 template:
   metadata:
     creationTimestamp: null
     labels:
       name: fluentd-log-agent
   spec:
     serviceAccountName: default
     tolerations:
       - key: node-role.kubernetes.io/master
         effect: NoSchedule
     containers:
       - image: celotestnet.azurecr.io/fluentd/google-fluentd:latest
         imagePullPolicy: Always
         name: fluentd-log-agent
         resources:
           limits:
             memory: "250Mi"
             cpu: 250m
           requests:
             memory: "250Mi"
             cpu: 100m
         volumeMounts:
           - mountPath: /var/log
             name: varlog
           - mountPath: /var/lib/docker/containers
             name: varlibdockercontainers
             readOnly: true
           - mountPath: /opt/credentials.json
             name: credentials.json
             readOnly: true
           - mountPath: /etc/google-fluentd/google-fluentd.conf
             name: google-fluentd.conf
             readOnly: true
           - mountPath: /etc/google-fluentd/config.d/app.conf
             name: app.conf
             readOnly: true
         env:
           - name: GOOGLE_APPLICATION_CREDENTIALS
             value: /opt/credentials.json
     restartPolicy: Always
     terminationGracePeriodSeconds: 30
     volumes:
       - hostPath:
           path: /var/log
         name: varlog
       - hostPath:
           path: /var/lib/docker/containers
         name: varlibdockercontainers
       - name: credentials.json
         configMap:
           name: logging-agent-config
       - name: app.json
         configMap:
           name: logging-agent-config
       - name: google-fluentd.json
         configMap:
           name: logging-agent-config




