apiVersion: v1
kind: ConfigMap
metadata:
  name: eksportisto-{{ .Values.deploymentSuffix }}-config
data:
  sensitive-accounts.json: {{ .Values.sensitiveAccountsBase64 | b64dec | quote }}
  service-account.json: {{ .Values.serviceAccountBase64 | b64dec | quote }}
  config.yaml: |
    monitoring:
      port: 8080
      address: 0.0.0.0
      requestTimeoutSeconds: 25

    redis:
      address: {{ .Release.Name }}-redis-headless:6379
      password: ""
      db: 0

    sensitiveAccountsFilePath: /var/config/sensitive-accounts.json

    publisher:
      backfill: 
        enabled: true
        startBlock: 0
        batchSize: 40000
        tipBuffer: 3
        sleepIntervalMilliseconds: 2000
      chainTip:
        enabled: true

    indexer:
      concurrency: 10
      bigquery:
        projectID: celo-testnet-production
        dataset: {{ .Values.bigquery.dataset }}
        table: data
      destination: bigquery
      dequeueTimeoutMilliseconds: 5000
      blockRetryAttempts: 3
      blockRetryDelayMilliseconds: 1000
