apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-api-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location ~ /admin/.* {
        deny all;
      }
spec:
  tls:
  - hosts:
    - {{ .Release.Name }}-api.{{ .Values.domain.name }}.org
    secretName: {{ .Release.Name }}-api-tls
  rules:
  - host: {{ .Release.Name }}-api.{{ .Values.domain.name }}.org
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Release.Name }}-api
            port:
              number: 4000
          serviceName: {{ .Release.Name }}-api
          servicePort: 4000
