name: Protocol Foundry tests
on: [push, pull_request]

jobs:
  check:
    defaults:
      run:
        working-directory: packages/protocol
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install forge dependencies
        run: forge install

      - name: Run tests
        run: forge test -vvv --use solc:0.5.13