apiVersion: pingcap.com/v1alpha1
kind: TimeChaos
metadata:
  name: pod-time-chaos
  namespace: scenario2
spec:
  mode: fixed
  timeOffset: "2h45m"
  value: "1"
  duration: "1m"
  clockIds:
    - CLOCK_REALTIME
  selector:
    namespaces:
      - scenario2
    labelSelectors:
      "app": "test"
  scheduler:
    cron: "@every 2m"

